<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>netcoreapp3.1;net8.0</TargetFrameworks>
        <LangVersion>8</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FeatureHubSDK\FeatureHubSDK.csproj" />
    </ItemGroup>

</Project>
