/*
 * FeatureServiceApi
 *
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = IO.FeatureHub.SSE.Client.OpenAPIDateConverter;

namespace IO.FeatureHub.SSE.Model
{
    /// <summary>
    /// BaseRolloutStrategyAttribute
    /// </summary>
    [DataContract(Name = "BaseRolloutStrategyAttribute")]
    public partial class BaseRolloutStrategyAttribute
    {

        /// <summary>
        /// Gets or Sets Conditional
        /// </summary>
        [DataMember(Name = "conditional", EmitDefaultValue = false)]
        public RolloutStrategyAttributeConditional? Conditional { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public RolloutStrategyFieldType? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="BaseRolloutStrategyAttribute" /> class.
        /// </summary>
        /// <param name="conditional">conditional.</param>
        /// <param name="fieldName">fieldName.</param>
        /// <param name="values">the value(s) associated with this rule.</param>
        /// <param name="type">type.</param>
        public BaseRolloutStrategyAttribute(RolloutStrategyAttributeConditional? conditional = default, string fieldName = default, List<Object> values = default, RolloutStrategyFieldType? type = default)
        {
            this.Conditional = conditional;
            this.FieldName = fieldName;
            this.Values = values;
            this.Type = type;
        }

        /// <summary>
        /// Gets or Sets FieldName
        /// </summary>
        [DataMember(Name = "fieldName", EmitDefaultValue = false)]
        public string FieldName { get; set; }

        /// <summary>
        /// the value(s) associated with this rule
        /// </summary>
        /// <value>the value(s) associated with this rule</value>
        [DataMember(Name = "values", EmitDefaultValue = false)]
        public List<Object> Values { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BaseRolloutStrategyAttribute {\n");
            sb.Append("  Conditional: ").Append(Conditional).Append("\n");
            sb.Append("  FieldName: ").Append(FieldName).Append("\n");
            sb.Append("  Values: ").Append(Values).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
