/*
 * FeatureServiceApi
 *
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = IO.FeatureHub.SSE.Client.OpenAPIDateConverter;

namespace IO.FeatureHub.SSE.Model
{
    /// <summary>
    /// FeatureStateUpdate
    /// </summary>
    [DataContract(Name = "FeatureStateUpdate")]
    public partial class FeatureStateUpdate
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureStateUpdate" /> class.
        /// </summary>
        /// <param name="value">the new value.</param>
        /// <param name="updateValue">indicates whether you are trying to update the value, as value can be null.</param>
        /// <param name="varLock">set only if you wish to lock or unlock, otherwise null.</param>
        public FeatureStateUpdate(Object value = default, bool updateValue = default, bool varLock = default)
        {
            this.Value = value;
            this.UpdateValue = updateValue;
            this.Lock = varLock;
        }

        /// <summary>
        /// the new value
        /// </summary>
        /// <value>the new value</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public Object Value { get; set; }

        /// <summary>
        /// indicates whether you are trying to update the value, as value can be null
        /// </summary>
        /// <value>indicates whether you are trying to update the value, as value can be null</value>
        [DataMember(Name = "updateValue", EmitDefaultValue = true)]
        public bool UpdateValue { get; set; }

        /// <summary>
        /// set only if you wish to lock or unlock, otherwise null
        /// </summary>
        /// <value>set only if you wish to lock or unlock, otherwise null</value>
        [DataMember(Name = "lock", EmitDefaultValue = true)]
        public bool Lock { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FeatureStateUpdate {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  UpdateValue: ").Append(UpdateValue).Append("\n");
            sb.Append("  Lock: ").Append(Lock).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
