/*
 * FeatureServiceApi
 *
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = IO.FeatureHub.SSE.Client.OpenAPIDateConverter;

namespace IO.FeatureHub.SSE.Model
{
    /// <summary>
    /// This is the model for the rollout strategy as required by Dacha and Edge
    /// </summary>
    [DataContract(Name = "FeatureRolloutStrategy")]
    public partial class FeatureRolloutStrategy
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureRolloutStrategy" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FeatureRolloutStrategy() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureRolloutStrategy" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="percentage">value between 0 and 1000000 - for four decimal places.</param>
        /// <param name="percentageAttributes">if you don&#39;t wish to apply percentage based on user id, you can use one or more attributes defined here.</param>
        /// <param name="value">when we attach the RolloutStrategy for Dacha or SSE this lets us push the value out. Only visible in SDK and SSE Edge..</param>
        /// <param name="attributes">attributes.</param>
        public FeatureRolloutStrategy(string id = default, int percentage = default, List<string> percentageAttributes = default, Object value = default, List<FeatureRolloutStrategyAttribute> attributes = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for FeatureRolloutStrategy and cannot be null");
            }
            this.Id = id;
            this.Percentage = percentage;
            this.PercentageAttributes = percentageAttributes;
            this.Value = value;
            this.Attributes = attributes;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// value between 0 and 1000000 - for four decimal places
        /// </summary>
        /// <value>value between 0 and 1000000 - for four decimal places</value>
        [DataMember(Name = "percentage", EmitDefaultValue = false)]
        public int Percentage { get; set; }

        /// <summary>
        /// if you don&#39;t wish to apply percentage based on user id, you can use one or more attributes defined here
        /// </summary>
        /// <value>if you don&#39;t wish to apply percentage based on user id, you can use one or more attributes defined here</value>
        [DataMember(Name = "percentageAttributes", EmitDefaultValue = false)]
        public List<string> PercentageAttributes { get; set; }

        /// <summary>
        /// when we attach the RolloutStrategy for Dacha or SSE this lets us push the value out. Only visible in SDK and SSE Edge.
        /// </summary>
        /// <value>when we attach the RolloutStrategy for Dacha or SSE this lets us push the value out. Only visible in SDK and SSE Edge.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public Object Value { get; set; }

        /// <summary>
        /// Gets or Sets Attributes
        /// </summary>
        [DataMember(Name = "attributes", EmitDefaultValue = false)]
        public List<FeatureRolloutStrategyAttribute> Attributes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FeatureRolloutStrategy {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Percentage: ").Append(Percentage).Append("\n");
            sb.Append("  PercentageAttributes: ").Append(PercentageAttributes).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
