/*
 * FeatureServiceApi
 *
 * This describes the API clients use for accessing features
 *
 * The version of the OpenAPI document: 1.1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = IO.FeatureHub.SSE.Client.OpenAPIDateConverter;

namespace IO.FeatureHub.SSE.Model
{
    /// <summary>
    /// FeatureState
    /// </summary>
    [DataContract(Name = "FeatureState")]
    public partial class FeatureState
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public FeatureValueType? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureState" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FeatureState() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FeatureState" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="key">key (required).</param>
        /// <param name="l">Is this feature locked. Usually this doesn&#39;t matter because the value is the value, but for FeatureInterceptors it can matter..</param>
        /// <param name="varVersion">The version of the feature, this allows features to change values and it means we don&#39;t trigger events.</param>
        /// <param name="type">type.</param>
        /// <param name="value">the current value.</param>
        /// <param name="environmentId">This field is filled in from the client side in the GET api as the GET api is able to request multiple environments. It is never passed from the server, as an array of feature states is wrapped in an environment..</param>
        /// <param name="strategies">strategies.</param>
        public FeatureState(Guid id = default, string key = default, bool l = default, long varVersion = default, FeatureValueType? type = default, Object value = default, Guid environmentId = default, List<FeatureRolloutStrategy> strategies = default)
        {
            this.Id = id;
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for FeatureState and cannot be null");
            }
            this.Key = key;
            this.L = l;
            this.VarVersion = varVersion;
            this.Type = type;
            this.Value = value;
            this.EnvironmentId = environmentId;
            this.Strategies = strategies;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Is this feature locked. Usually this doesn&#39;t matter because the value is the value, but for FeatureInterceptors it can matter.
        /// </summary>
        /// <value>Is this feature locked. Usually this doesn&#39;t matter because the value is the value, but for FeatureInterceptors it can matter.</value>
        [DataMember(Name = "l", EmitDefaultValue = true)]
        public bool L { get; set; }

        /// <summary>
        /// The version of the feature, this allows features to change values and it means we don&#39;t trigger events
        /// </summary>
        /// <value>The version of the feature, this allows features to change values and it means we don&#39;t trigger events</value>
        [DataMember(Name = "version", EmitDefaultValue = false)]
        public long VarVersion { get; set; }

        /// <summary>
        /// the current value
        /// </summary>
        /// <value>the current value</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public Object Value { get; set; }

        /// <summary>
        /// This field is filled in from the client side in the GET api as the GET api is able to request multiple environments. It is never passed from the server, as an array of feature states is wrapped in an environment.
        /// </summary>
        /// <value>This field is filled in from the client side in the GET api as the GET api is able to request multiple environments. It is never passed from the server, as an array of feature states is wrapped in an environment.</value>
        [DataMember(Name = "environmentId", EmitDefaultValue = false)]
        public Guid EnvironmentId { get; set; }

        /// <summary>
        /// Gets or Sets Strategies
        /// </summary>
        [DataMember(Name = "strategies", EmitDefaultValue = false)]
        public List<FeatureRolloutStrategy> Strategies { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FeatureState {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  L: ").Append(L).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  EnvironmentId: ").Append(EnvironmentId).Append("\n");
            sb.Append("  Strategies: ").Append(Strategies).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
