:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\ToDoAspCore
dotnet build src\ToDoAspCore
echo Now, run the following to start the project: dotnet run -p src\ToDoAspCore\ToDoAspCore.csproj --launch-profile web.
echo.
