:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\ToDoAspCoreExample
dotnet build src\ToDoAspCoreExample
echo Now, run the following to start the project: dotnet run -p src\ToDoAspCoreExample\ToDoAspCoreExample.csproj --launch-profile web.
echo.
