name: publish to nuget
on:
  workflow_dispatch:
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # enable GitHub OIDC token issuance for this job
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Pack
        run: dotnet pack --configuration Release --no-restore
      # Use the ambient GitHub token to login to NuGet and retrieve an API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          # Secret is your NuGet username, e.g. andrewlock
          user: ${{ secrets.NUGET_USER }}
      - name: push to NuGet
        shell: pwsh
        run: |            
            dotnet nuget push FeatureHubSDK/FeatureHubSDK.csproj `
              --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" `
              --source https://api.nuget.org/v3/index.json
                  
