name: Build and test .Net SDK

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
      - name: Restore
        run: dotnet restore
      - name: Check formatting
        run: dotnet format FeatureHubSDK.sln --verify-no-changes
      - name: Build
        run: dotnet build FeatureHubSDK.sln --configuration Release --no-restore
      - name: Pack FeatureHubSDK
        working-directory: FeatureHubSDK
        run: dotnet pack /p:PackageVersion=1.0.0 --configuration Release --no-build
      - name: Pack FeatureHubInterceptorYaml
        working-directory: FeatureHubInterceptorYaml
        run: dotnet pack /p:PackageVersion=1.0.0 --configuration Release --no-build
      - name: Pack FeatureHubUsageOpenTelemetry
        working-directory: FeatureHubUsageOpenTelemetry
        run: dotnet pack /p:PackageVersion=1.0.0 --configuration Release --no-build
      - name: Test
        run: dotnet test FeatureHubSDK.sln
