name: Build and test .Net SDK

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Check formatting
        run: dotnet format FeatureHubSDK.sln --verify-no-changes
      - name: Restore
        working-directory: FeatureHubSDK
        run: dotnet restore
      - name: Build
        working-directory: FeatureHubSDK
        run: dotnet build /p:PackageVersion=1.0.0 /p:PackageReleaseNotes="1.0.0 - EventSource library dependency update." --configuration Release
      - name: Pack
        working-directory: FeatureHubSDK
        run: dotnet pack /p:PackageVersion=1.0.0 /p:PackageReleaseNotes="1.0.0 - EventSource library dependency update." --configuration Release
      - name: Install dependencies
        run: dotnet restore
      - name: Pack
        run: dotnet pack --configuration Release --no-restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test
